from __future__ import annotations

CATALOG: dict[str, str] = {
    # Application / navigation
    "app.name": "WizZ Desktop",
    "nav.home": "Home",
    "nav.color": "Color",
    "nav.scenes": "Scenes",
    "nav.favorites": "Favorites",
    "nav.routines": "Routines",
    "nav.settings": "Settings",
    "nav.hotkeys": "Hotkeys",

    # Common actions and states
    "common.apply": "Apply",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.close": "Close",
    "common.open": "Open",
    "common.add": "Add",
    "common.remove": "Remove",
    "common.rename": "Rename",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.search": "Search",
    "common.refresh": "Refresh",
    "common.settings": "Settings",
    "common.on": "On",
    "common.off": "Off",
    "common.online": "Online",
    "common.offline": "Offline",
    "common.enabled": "Enabled",
    "common.disabled": "Disabled",
    "common.none": "None",
    "common.system_default": "System default",
    "common.ready": "Ready",
    "common.error": "Error",

    # Language settings
    "language.section": "LANGUAGE",
    "language.title": "Application language",
    "language.description": "Choose the language used by the interface and tray menu.",
    "language.system": "System default",
    "language.english": "English",
    "language.spanish": "Spanish",
    "language.changed": "Language changed to {language}.",
    "language.restart_not_required": "The interface updates without restarting WizZ Desktop.",

    # Bulbs / discovery
    "bulbs.section": "LIGHTS",
    "bulbs.search": "Search for lights",
    "bulbs.searching": "Searching for WiZ lights on the local network…",
    "bulbs.search_done.one": "Search complete · {count} light available.",
    "bulbs.search_done.other": "Search complete · {count} lights available.",
    "bulbs.search_error": "Search finished with an error: {error}",
    "bulbs.search_not_started": "The search could not be started yet.",
    "bulbs.none": "No lights found. Select “Search”.",
    "bulbs.add_by_ip": "Add by IP",
    "bulbs.ip_address": "IP address",
    "bulbs.active": "Active light",
    "bulbs.use_as_active": "Use as active light",
    "bulbs.all": "All detected lights",
    "bulbs.single": "One light",
    "bulbs.rename": "Rename light",
    "bulbs.remove": "Remove light",
    "bulbs.removed": "Light removed. “Search for lights” can detect it again.",
    "bulbs.already_removed": "The light was no longer registered.",
    "bulbs.no_mac": "no MAC",
    "bulbs.no_response": "No response",
    "bulbs.info": "Light information",

    # Home / light state
    "home.title": "Lighting control",
    "home.subtitle": "Local WiZ control over your LAN",
    "light.turn_on": "Turn on",
    "light.turn_off": "Turn off",
    "light.toggle": "Toggle",
    "light.brightness": "Brightness",
    "light.color": "Color",
    "light.white": "White",
    "light.temperature": "Color temperature",

    # Color Studio
    "color_studio.title": "Color Studio",
    "color_studio.color": "Color",
    "color_studio.white": "White",
    "color_studio.precise": "Precise",
    "color_studio.live_apply": "Apply live",
    "color_studio.pending": "Pending",
    "color_studio.hue": "Hue",
    "color_studio.purity": "Purity",
    "color_studio.recent": "Recent colors",
    "color_studio.quick_colors": "Quick colors",
    "color_studio.warm": "Warm",
    "color_studio.neutral": "Neutral",
    "color_studio.cool": "Cool",

    # Favorites / routines / hotkeys
    "favorites.title": "Favorites",
    "favorites.subtitle": "Saved colors, whites, scenes and brightness",

    "favorites.new": "New",
    "favorites.edit": "Edit",
    "favorites.delete": "Delete",

    "favorites.empty": "No favorites yet.",

    "favorites.name": "Name",
    "favorites.type": "Type",
    "favorites.hex": "HEX",

    "favorites.hue": "Hue",
    "favorites.saturation": "Intensity",
    "favorites.lightness": "Lightness",

    "favorites.scene": "Scene",
    "favorites.wiz_scene": "WiZ Scene",
    "favorites.speed_value": "Speed {value}",
    "favorites.brightness_value": "Brightness {value}%",
    "favorites.scene_summary": "{scene} · speed {speed}",

    "favorites.cancel": "Cancel",
    "favorites.save": "Save",

    "favorites.new_title": "New favorite",
    "favorites.edit_title": "Edit favorite",

    "favorites.default_name": "New favorite",

    "routines.title": "Routines",
    "routines.empty": "No routines yet.",
    "hotkeys.title": "Global hotkeys",
    "hotkeys.description": "Control WizZ Desktop while another application is focused.",

    # Tray
    "tray.show_app": "Open WizZ Desktop",
    "tray.hide_app": "Hide WizZ Desktop",
    "tray.quick_panel": "Quick Panel",
    "tray.settings": "Settings",
    "tray.exit": "Exit",
    "tray.no_light": "No active light",
    "tray.all_lights": "All lights",

    # Quick Panel
    "quick.title": "Quick Panel",
    "quick.open_full": "Open WizZ Desktop",
    "quick.open_settings": "Open Settings",
    "quick.no_connection": "Offline",
    "quick.no_active_light": "No active light",
    "quick.favorites": "Favorites",
    "quick.whites": "Whites",
    "quick.colors": "Colors",
    "quick.press_escape": "Press Esc to close",

    # Desktop/runtime
    "runtime.background": "STARTUP AND BACKGROUND",
    "runtime.tray_enabled": "Enable system tray",
    "runtime.close_to_tray": "Close to tray",
    "runtime.open_minimized": "Open minimized",
    "runtime.start_with_windows": "Start with Windows",
    "runtime.saved": "Background settings saved.",

    # About
    "about.title": "ABOUT",
    "about.local_control": "Local WiZ control · cloud not required",
    "about.data": "Data",
    "about.logs": "Logs",


    # Settings language integration
    'language.selector': 'Idioma / Language',
    'language.effective': 'Effective language: {language}',
    'language.detected': 'Windows language: {language}',
    'settings.title': 'Settings',
    'settings.subtitle': 'Targets, discovery and light management',
    'settings.target.section': 'TARGET',
    'settings.target.mode': 'Control mode',
    'settings.target.help': 'The target only determines which IP receives commands.',
    'settings.slider_performance': 'Slider performance',
    'settings.slider.35': '35 ms · ultra fast / more CPU',
    'settings.slider.65': '65 ms · recommended',
    'settings.slider.90': '90 ms · smooth / less CPU',
    'settings.slider.130': '130 ms · CPU saving',
    'settings.cleanup_offline': 'Remove offline',
    'settings.cleanup_title': 'Cleanup complete',
    'settings.cleanup_result': 'Removed {count} offline IPs.',
    'runtime.tray_enabled.description': 'Keep WizZ available next to the clock.',
    'runtime.close_to_tray.description': 'The X hides the window instead of exiting.',
    'runtime.open_minimized.description': 'Start hidden when the tray is enabled.',
    'runtime.start_with_windows.description': 'Add or remove automatic startup.',
    'runtime.restart_hint': 'Tray changes work best after restarting the app. Development mode does not force window restoration.',
    'about.storage_hint': 'In the packaged app, settings and logs live in persistent application storage and survive updates.',
    'common.information': 'Information',
    'common.name': 'Name',
    'common.ok': 'OK',
    'bulbs.mode.single': 'One light',
    'bulbs.mode.all': 'All detected lights',
    'bulbs.status.online': '● online · {label}{kelvin}',
    'bulbs.status.offline': '○ no response',
    'bulbs.cleanup_removed.one': 'Removed {count} offline IP.',
    'bulbs.cleanup_removed.other': 'Removed {count} offline IPs.',
    'bulbs.rename_title': 'Rename light',
    'bulbs.add_title': 'Add by IP',
    'bulbs.active_badge': 'ACTIVE',
    'bulbs.target_badge': 'TARGET',
    'about.product_subtitle': 'Local WiZ control · cloud not required',
}

# v1.1 Home and Color Studio
CATALOG.update({'color.name.blue': 'Blue', 'color.name.cyan': 'Cyan', 'color.name.green': 'Green', 'color.name.lime': 'Lime', 'color.name.magenta': 'Magenta', 'color.name.orange': 'Orange', 'color.name.pink': 'Pink', 'color.name.red': 'Red', 'color.name.sky': 'Sky blue', 'color.name.violet': 'Violet', 'color.name.yellow': 'Yellow', 'color_studio.applied': 'Applied', 'color_studio.apply_error': 'Could not apply: {error}', 'color_studio.apply_section': 'APPLICATION', 'color_studio.apply_subtitle': 'Immediate delivery with safe throttling', 'color_studio.brightness_subtitle': 'Real light dimming', 'color_studio.brightness_value': 'Brightness {value}%', 'color_studio.cct_section': 'CCT WHITES', 'color_studio.cct_subtitle': 'Real WiZ temperature, independent from RGB', 'color_studio.detected_range': 'Detected range: {minimum}K – {maximum}K', 'color_studio.direct_rgb': 'Direct RGB · separate brightness', 'color_studio.exact_note': 'Exact RGB preserved ({value}%). Using the palette returns to the perceptual model with separate brightness.', 'color_studio.exact_preserved': 'Exact RGB preserved', 'color_studio.favorite_default': 'Favorite', 'color_studio.favorites_empty': 'Save the current color to create quick shortcuts.', 'color_studio.favorites_section': 'QUICK FAVORITES', 'color_studio.favorites_subtitle': 'Saved shortcuts in WizZ', 'color_studio.hue_purity': 'H {hue}° · Purity {purity}% · Brightness {brightness}%', 'color_studio.hue_saturation': 'H {hue}° · S {saturation}% · Exact RGB', 'color_studio.live': 'Live', 'color_studio.live_hint': 'Visual changes are sent with throttling; dragging does not flood the LAN.', 'color_studio.mode_white': 'WHITE', 'color_studio.no_pending_changes': 'No pending changes.', 'color_studio.palette_hint': '↑ white / pastel   ·   ↓ pure color', 'color_studio.palette_note': 'The palette generates direct RGB with perceptual purity; use Brightness for intensity.', 'color_studio.palette_section': 'HUE / PURITY PALETTE', 'color_studio.palette_subtitle': 'Horizontal: hue · vertical: perceptual purity · no black', 'color_studio.pending_changes': 'Pending changes', 'color_studio.precise_section': 'PRECISE CONTROL', 'color_studio.precise_subtitle': 'Exact RGB is preserved until the palette is used again', 'color_studio.quick_subtitle': 'Clean colors at 100%', 'color_studio.recent_section': 'RECENT', 'color_studio.recent_subtitle': 'Last applied colors and whites', 'color_studio.recents_empty': 'No recent colors yet. Apply one to save it here.', 'color_studio.save_current': 'Save current', 'color_studio.subtitle': 'Pure color, Kelvin whites and independent brightness', 'color_studio.use_values': 'Use values', 'color_studio.view_all': 'View all', 'color_studio.white_value': 'White {kelvin}K', 'home.brightness_section': 'BRIGHTNESS', 'home.favorites_empty': 'Save colors or whites from Color Studio or Favorites.', 'home.favorites_section': 'FAVORITES', 'home.header.subtitle': 'Main lighting controls', 'home.header.title': 'Home', 'home.manage': 'Manage', 'home.master': 'Master control', 'home.master_hint': 'Select to toggle the active target', 'home.off': 'OFF', 'home.on': 'ON', 'home.quick.cinema': 'TV / Cinema', 'home.quick.cool': 'Cool', 'home.quick.party': 'Party', 'home.quick.reading': 'Reading', 'home.quick.relax': 'Relax', 'home.quick.reset': 'Reset', 'home.quick.warm': 'Warm', 'home.quick_section': 'QUICK ACTIONS', 'home.refresh_state': 'Refresh real device state', 'home.reset_brightness': 'Restore brightness to 100%', 'home.searching': 'Searching…', 'home.status.no_target': 'No active light', 'home.status.offline': 'Offline', 'home.status.online': 'Online', 'white.name.candle': 'Candle', 'white.name.cool': 'Cool', 'white.name.daylight': 'Daylight', 'white.name.home': 'Home', 'white.name.neutral': 'Neutral', 'white.name.warm': 'Warm', 'white.note.daily': 'daily', 'white.note.energy': 'energy', 'white.note.focus': 'focus', 'white.note.relax': 'relax', 'white.note.soft': 'soft', 'white.note.very_warm': 'very warm'})
