from __future__ import annotations

CATALOG: dict[str, str] = {
    # Application / navigation
    "app.name": "WizZ Desktop",
    "nav.home": "Home",
    "nav.color": "Color",
    "nav.scenes": "Scenes",
    "nav.favorites": "Favorites",
    "nav.routines": "Routines",
    "nav.settings": "Settings",
    "nav.hotkeys": "Hotkeys",

    # Common actions and states
    "common.apply": "Apply",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.close": "Close",
    "common.open": "Open",
    "common.add": "Add",
    "common.remove": "Remove",
    "common.rename": "Rename",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.search": "Search",
    "common.refresh": "Refresh",
    "common.settings": "Settings",
    "common.on": "On",
    "common.off": "Off",
    "common.online": "Online",
    "common.offline": "Offline",
    "common.enabled": "Enabled",
    "common.disabled": "Disabled",
    "common.none": "None",
    "common.system_default": "System default",
    "common.ready": "Ready",
    "common.error": "Error",

    # Language settings
    "language.section": "LANGUAGE",
    "language.title": "Application language",
    "language.description": "Choose the language used by the interface and tray menu.",
    "language.system": "System default",
    "language.english": "English",
    "language.spanish": "Spanish",
    "language.changed": "Language changed to {language}.",
    "language.restart_not_required": "The interface updates without restarting WizZ Desktop.",

    # Bulbs / discovery
    "bulbs.section": "LIGHTS",
    "bulbs.search": "Search for lights",
    "bulbs.searching": "Searching for WiZ lights on the local network…",
    "bulbs.search_done.one": "Search complete · {count} light available.",
    "bulbs.search_done.other": "Search complete · {count} lights available.",
    "bulbs.search_error": "Search finished with an error: {error}",
    "bulbs.search_not_started": "The search could not be started yet.",
    "bulbs.none": "No lights found. Select “Search”.",
    "bulbs.add_by_ip": "Add by IP",
    "bulbs.ip_address": "IP address",
    "bulbs.active": "Active light",
    "bulbs.use_as_active": "Use as active light",
    "bulbs.all": "All detected lights",
    "bulbs.single": "One light",
    "bulbs.rename": "Rename light",
    "bulbs.remove": "Remove light",
    "bulbs.removed": "Light removed. “Search for lights” can detect it again.",
    "bulbs.already_removed": "The light was no longer registered.",
    "bulbs.no_mac": "no MAC",
    "bulbs.no_response": "No response",
    "bulbs.info": "Light information",

    # Home / light state
    "home.title": "Lighting control",
    "home.subtitle": "Local WiZ control over your LAN",
    "light.turn_on": "Turn on",
    "light.turn_off": "Turn off",
    "light.toggle": "Toggle",
    "light.brightness": "Brightness",
    "light.color": "Color",
    "light.white": "White",
    "light.temperature": "Color temperature",

    # Color Studio
    "color_studio.title": "Color Studio",
    "color_studio.color": "Color",
    "color_studio.white": "White",
    "color_studio.precise": "Precise",
    "color_studio.live_apply": "Apply live",
    "color_studio.pending": "Pending",
    "color_studio.hue": "Hue",
    "color_studio.purity": "Purity",
    "color_studio.recent": "Recent colors",
    "color_studio.quick_colors": "Quick colors",
    "color_studio.warm": "Warm",
    "color_studio.neutral": "Neutral",
    "color_studio.cool": "Cool",

    # Favorites / routines / hotkeys
    "favorites.title": "Favorites",
    "favorites.subtitle": "Saved colors, whites, scenes and brightness",

    "favorites.new": "New",
    "favorites.edit": "Edit",
    "favorites.delete": "Delete",

    "favorites.empty": "No favorites yet.",

    "favorites.name": "Name",
    "favorites.type": "Type",
    "favorites.hex": "HEX",

    "favorites.hue": "Hue",
    "favorites.saturation": "Intensity",
    "favorites.lightness": "Lightness",

    "favorites.scene": "Scene",
    "favorites.wiz_scene": "WiZ Scene",
    "favorites.speed_value": "Speed {value}",
    "favorites.brightness_value": "Brightness {value}%",
    "favorites.scene_summary": "{scene} · speed {speed}",

    "favorites.cancel": "Cancel",
    "favorites.save": "Save",

    "favorites.new_title": "New favorite",
    "favorites.edit_title": "Edit favorite",

    "favorites.default_name": "New favorite",

    "routines.title": "Routines",
    "routines.empty": "No routines yet.",
    "hotkeys.title": "Global hotkeys",
    "hotkeys.description": "Control WizZ Desktop while another application is focused.",

    # Tray
    "tray.show_app": "Open WizZ Desktop",
    "tray.hide_app": "Hide WizZ Desktop",
    "tray.quick_panel": "Quick Panel",
    "tray.settings": "Settings",
    "tray.exit": "Exit",
    "tray.no_light": "No active light",
    "tray.all_lights": "All lights",

    # Quick Panel
    "quick.title": "Quick Panel",
    "quick.open_full": "Open WizZ Desktop",
    "quick.open_settings": "Open Settings",
    "quick.no_connection": "Offline",
    "quick.no_active_light": "No active light",
    "quick.favorites": "Favorites",
    "quick.whites": "Whites",
    "quick.colors": "Colors",
    "quick.press_escape": "Press Esc to close",

    # Desktop/runtime
    "runtime.background": "STARTUP AND BACKGROUND",
    "runtime.tray_enabled": "Enable system tray",
    "runtime.close_to_tray": "Close to tray",
    "runtime.open_minimized": "Open minimized",
    "runtime.start_with_windows": "Start with Windows",
    "runtime.saved": "Background settings saved.",

    # About
    "about.title": "ABOUT",
    "about.local_control": "Local WiZ control · cloud not required",
    "about.data": "Data",
    "about.logs": "Logs",


    # Settings language integration
    'language.selector': 'Idioma / Language',
    'language.effective': 'Effective language: {language}',
    'language.detected': 'Windows language: {language}',
    'settings.title': 'Settings',
    'settings.subtitle': 'Targets, discovery and light management',
    'settings.target.section': 'TARGET',
    'settings.target.mode': 'Control mode',
    'settings.target.help': 'The target only determines which IP receives commands.',
    'settings.slider_performance': 'Slider performance',
    'settings.slider.35': '35 ms · ultra fast / more CPU',
    'settings.slider.65': '65 ms · recommended',
    'settings.slider.90': '90 ms · smooth / less CPU',
    'settings.slider.130': '130 ms · CPU saving',
    'settings.cleanup_offline': 'Remove offline',
    'settings.cleanup_title': 'Cleanup complete',
    'settings.cleanup_result': 'Removed {count} offline IPs.',
    'runtime.tray_enabled.description': 'Keep WizZ available next to the clock.',
    'runtime.close_to_tray.description': 'The X hides the window instead of exiting.',
    'runtime.open_minimized.description': 'Start hidden when the tray is enabled.',
    'runtime.start_with_windows.description': 'Add or remove automatic startup.',
    'runtime.restart_hint': 'Tray changes work best after restarting the app. Development mode does not force window restoration.',
    'about.storage_hint': 'In the packaged app, settings and logs live in persistent application storage and survive updates.',
    'common.information': 'Information',
    'common.name': 'Name',
    'common.ok': 'OK',
    'bulbs.mode.single': 'One light',
    'bulbs.mode.all': 'All detected lights',
    'bulbs.status.online': '● online · {label}{kelvin}',
    'bulbs.status.offline': '○ no response',
    'bulbs.cleanup_removed.one': 'Removed {count} offline IP.',
    'bulbs.cleanup_removed.other': 'Removed {count} offline IPs.',
    'bulbs.rename_title': 'Rename light',
    'bulbs.add_title': 'Add by IP',
    'bulbs.active_badge': 'ACTIVE',
    'bulbs.target_badge': 'TARGET',
    'about.product_subtitle': 'Local WiZ control · cloud not required',
}

# Full application interface
CATALOG.update({
    "common.yes": "Yes",
    "common.no": "No",
    "common.type": "Type",
    "common.value": "Value",
    "common.description": "Description",
    "common.icon": "Icon",
    "common.actions": "ACTIONS",
    "common.duplicate": "Duplicate",
    "common.move_up": "Move up",
    "common.move_down": "Move down",
    "common.test": "Test",
    "common.record": "Record",
    "common.export": "Export",
    "common.restore_defaults": "Restore defaults",
    "common.status": "STATUS",
    "common.percent_value": "{value}%",
    "common.kelvin_value": "{value}K",
    "color_studio.preset_tooltip": "{name} · {value}",
    "color_studio.white_detail": "{name} · Brightness {brightness}%",
    "color_studio.hue_purity_short": "H {hue}° · Purity {purity}%",
    "color_studio.cct_detail": "{kelvin}K · {name}",
    "home.status.active": "{active}/{count} online{extra}",
    "home.status.saved.one": "{count} saved · no response",
    "home.status.saved.other": "{count} saved · no response",
    "home.status.no_bulbs": "No lights",
    "home.target_summary": "target: {mode} · {ip}",
    "home.capabilities.rgb_white": "RGB + Whites",
    "home.capabilities.white": "Whites",
    "home.capabilities.none": "No capabilities",
    "settings.open_folder_error": "Could not open the folder: {error}",
    "settings.info.name": "Name",
    "settings.info.online": "Online",
    "settings.info.active": "Active",
    "settings.info.target": "Target",
    "settings.info.module": "Module",
    "settings.info.firmware": "Firmware",
    "settings.info.state": "State",
    "settings.info.brightness": "Brightness",
    "settings.info.temperature": "Temperature",
    "settings.info.scene": "Scene",
    "settings.info.whites": "Whites",
    "settings.info.power_meter": "Power meter",
    "settings.info.model": "Model",
    "bulbs.target_badge": "TARGET",
    "bulbs.online_detail": "● online · {label}{range}",
    "bulbs.offline_detail": "○ no response",
    "bulbs.ip_example": "192.168.1.20",
    "runtime.startup.windows_only": "Start with Windows is only available on Windows.",
    "runtime.startup.update_error": "Could not update Start with Windows: {error}",
    "runtime.startup.updated": "Start with Windows updated.",
    "runtime.startup.disabled": "Start with Windows disabled.",
    "instance.already_running": "{app} is already running. Check the Windows notification area.",

    "scenes.title": "Scenes",
    "scenes.subtitle": "WiZ scenes and local custom scenes",
    "scenes.save_current": "Save current",
    "scenes.new": "New scene",
    "scenes.my_section": "MY SCENES",
    "scenes.wiz_section": "WIZ SCENES",
    "scenes.speed_section": "SCENE SPEED",
    "scenes.reset_speed": "Reset speed",
    "scenes.empty": "You do not have any custom scenes yet.",
    "scenes.dynamic": "dynamic",
    "scenes.static": "static",
    "scenes.custom_fallback": "My scene",
    "scenes.custom_type": "custom",
    "scenes.scene_summary": "Scene {scene_id} · speed {speed}",
    "scenes.capture_default_name": "Current scene",
    "scenes.capture_title": "Save current state",
    "scenes.type_rgb": "HEX color",
    "scenes.type_white": "Kelvin white",
    "scenes.type_wiz": "WiZ Scene",
    "scenes.edit_title": "Edit scene",
    "scenes.new_title": "New custom scene",
    "scenes.dynamic_speed": "Speed for dynamic scenes",
    "scene.group.favorites": "Favorites",
    "scene.group.nature": "Nature",
    "scene.group.ambience": "Ambience",
    "scene.group.whites": "Whites",
    "scene.group.routines": "Routines",
    "scene.group.holidays": "Holidays",
    "scene.name.1": "Ocean",
    "scene.name.2": "Romance",
    "scene.name.3": "Sunset",
    "scene.name.4": "Party",
    "scene.name.5": "Fireplace",
    "scene.name.6": "Cozy",
    "scene.name.7": "Forest",
    "scene.name.8": "Pastel",
    "scene.name.9": "Wake up",
    "scene.name.10": "Sleep",
    "scene.name.11": "Warm White",
    "scene.name.12": "Daylight",
    "scene.name.13": "Cool White",
    "scene.name.14": "Night Light",
    "scene.name.15": "Focus",
    "scene.name.16": "Relax",
    "scene.name.17": "True Colors",
    "scene.name.18": "TV / Cinema",
    "scene.name.19": "Plants",
    "scene.name.20": "Spring",
    "scene.name.21": "Summer",
    "scene.name.22": "Autumn",
    "scene.name.23": "Deep Dive",
    "scene.name.24": "Jungle",
    "scene.name.25": "Mojito",
    "scene.name.26": "Club",
    "scene.name.27": "Christmas",
    "scene.name.28": "Halloween",
    "scene.name.29": "Candlelight",
    "scene.name.30": "Golden White",
    "scene.name.31": "Pulse",
    "scene.name.32": "Steampunk",
    "scene.name.33": "Diwali",
})

CATALOG.update({
    "routines.subtitle": "Simple compound presets for hotkeys and quick actions",
    "routines.new": "New",
    "routines.capture_state": "Capture state",
    "routines.info": "Create visual routines without JSON: color, white, brightness, scene, favorites, wait and target.",
    "routines.restore_presets": "Restore presets",
    "routines.empty_full": "No routines.",
    "routines.fallback_name": "Routine",
    "routines.default_name": "New routine",
    "routines.no_actions": "No actions",
    "routines.apply": "Apply",
    "routines.capture_name": "Captured routine",
    "routines.capture_description": "Created from the current state",
    "routines.field.card_color": "Card color",
    "routines.add_action": "Add action",
    "routines.new_title": "New routine",
    "routines.edit_title": "Edit routine",
    "routines.action.edit": "Edit action",
    "routines.action.delete": "Delete action",
    "routines.action.label": "Action",
    "routines.action.no_config": "This action does not need configuration.",
    "routines.action.add_title": "Add action",
    "routines.action.edit_title": "Edit action",
    "routines.action.save": "Save action",
    "routines.action.no_value": "no value",
    "routines.action.not_found": "Not found",
    "routines.action.turn_on": "Turn on",
    "routines.action.turn_off": "Turn off",
    "routines.action.toggle": "Toggle",
    "routines.action.brightness": "Brightness",
    "routines.action.brightness_delta": "Brightness +/-",
    "routines.action.rgb": "Color",
    "routines.action.white_percent": "Warm/cool white",
    "routines.action.white_kelvin": "Kelvin white",
    "routines.action.scene": "WiZ Scene",
    "routines.action.favorite": "Favorite",
    "routines.action.custom_scene": "Custom scene",
    "routines.action.routine": "Another routine",
    "routines.action.wait": "Wait",
    "routines.action.target_mode": "Target",
    "routines.action.brightness_value": "Brightness {value}%",
    "routines.action.delta_value": "Change {value:+d}%",
    "routines.action.white_value": "White {percent}% · {kelvin}K",
    "routines.action.speed_value": "Speed {value}",
    "routines.action.wait_value": "Wait {value}ms",
    "routines.action.favorite_empty": "No favorites have been created.",
    "routines.action.custom_scene_empty": "No custom scenes have been created.",
    "routines.action.routine_empty": "No other routines are available.",
    "routines.target.single": "One light",
    "routines.target.all": "All",
    "routines.icon.auto": "Auto",
    "routines.icon.study": "Study",
    "routines.icon.night": "Night",
    "routines.icon.gaming": "Gaming",
    "routines.icon.cinema": "Cinema",
    "routines.icon.reading": "Reading",
    "routines.icon.power_off": "Power off",
    "routines.icon.color": "Color",
    "routines.icon.light": "Light",
    "routines.icon.routine": "Routine",
    "routines.copy_suffix": "copy",
    "routine.default.study.name": "Study mode",
    "routine.default.study.description": "Clear white and high brightness for working.",
    "routine.default.night.name": "Night mode",
    "routine.default.night.description": "Warm white and low brightness.",
    "routine.default.gaming.name": "Gaming mode",
    "routine.default.gaming.description": "Blue/purple with medium brightness.",
    "routine.default.cinema.name": "Cinema mode",
    "routine.default.cinema.description": "TV/Cinema scene with reduced brightness.",
    "routine.default.reading.name": "Reading mode",
    "routine.default.reading.description": "Comfortable neutral white.",
    "routine.default.soft_off.name": "Soft power off",
    "routine.default.soft_off.description": "Lower brightness briefly, then turn off.",
})

CATALOG.update({
    "hotkeys.subtitle": "Global shortcuts for lights, routines and favorites",
    "hotkeys.reregister": "Re-register",
    "hotkeys.enabled": "Hotkeys enabled",
    "hotkeys.enabled_help": "Global application service.",
    "hotkeys.suppress": "Capture keys",
    "hotkeys.suppress_help": "Only for the keyboard fallback.",
    "hotkeys.release": "Run on release",
    "hotkeys.release_help": "Keyboard; Windows uses debounce.",
    "hotkeys.debounce": "Debounce",
    "hotkeys.category": "Category",
    "hotkeys.search_action": "Search action",
    "hotkeys.search_hint": "cinema, red, night, brightness...",
    "hotkeys.action": "Action",
    "hotkeys.shortcut": "Shortcut",
    "hotkeys.shortcut_hint": "ctrl+alt+l",
    "hotkeys.create_section": "CREATE / EDIT SHORTCUT",
    "hotkeys.create_help": "Choose an action, record the combination and save. Conflicts are replaced with a warning.",
    "hotkeys.templates_section": "USEFUL TEMPLATES",
    "hotkeys.assigned_section": "CONFIGURED SHORTCUTS",
    "hotkeys.custom_color": "Custom color",
    "hotkeys.quick_colors": "Quick colors",
    "hotkeys.hue": "Hue",
    "hotkeys.intensity": "Intensity",
    "hotkeys.lightness": "Lightness",
    "hotkeys.unavailable": "unavailable",
    "hotkeys.choose_shortcut": "Choose or record a shortcut. Recommended: ctrl+alt+letter/arrow.",
    "hotkeys.conflict": "Conflict: it will replace '{action}'.",
    "hotkeys.valid": "Valid shortcut.",
    "hotkeys.empty": "No hotkeys assigned.",
    "hotkeys.recording": "Press keys...",
    "hotkeys.recording_help": "Recording. Press ESC to cancel.",
    "hotkeys.export_title": "Hotkeys JSON",
    "hotkeys.ms_value": "{value} ms",
    "hotkeys.group.general": "General",
    "hotkeys.group.target": "Target",
    "hotkeys.group.brightness": "Brightness",
    "hotkeys.group.whites": "Whites",
    "hotkeys.group.colors": "Colors",
    "hotkeys.group.custom_colors": "Custom colors",
    "hotkeys.group.wiz_scenes": "WiZ Scenes",
    "hotkeys.group.favorites": "Favorites",
    "hotkeys.group.my_scenes": "My scenes",
    "hotkeys.group.routines": "Routines",
    "hotkeys.group.custom": "Custom",
    "hotkeys.action.toggle": "Toggle power",
    "hotkeys.action.on": "Turn on",
    "hotkeys.action.off": "Turn off",
    "hotkeys.action.reset": "Reset light",
    "hotkeys.action.target_single": "One-light mode",
    "hotkeys.action.target_all": "All-lights mode",
    "hotkeys.action.bri_up": "Brightness +10%",
    "hotkeys.action.bri_down": "Brightness -10%",
    "hotkeys.action.brightness": "Brightness {value}%",
    "hotkeys.action.white_warm": "Warm white",
    "hotkeys.action.white_neutral": "Neutral white",
    "hotkeys.action.white_cold": "Cool white",
    "hotkeys.action.white_range": "White {value}% of range",
    "hotkeys.action.color_custom": "Custom color",
    "hotkeys.action.color_hex": "Color #{value}",
    "hotkeys.preset.toggle": "Toggle",
    "hotkeys.preset.bri_up": "Brightness +",
    "hotkeys.preset.bri_down": "Brightness -",
    "hotkeys.preset.red": "Red",
    "hotkeys.preset.cinema": "Cinema",
    "hotkeys.preset.night": "Night mode",
})

CATALOG.update({
    "hotkeys.status.disabled": "disabled",
    "hotkeys.status.native": "Windows native active{suffix}",
    "hotkeys.status.hybrid": "Windows + fallback active{suffix}",
    "hotkeys.status.keyboard": "global keyboard active{suffix}",
    "hotkeys.status.unregistered": "not registered",
    "hotkeys.status.empty": "no shortcuts",
    "hotkeys.dependency.native_recording_missing": "Native Windows hotkeys are available. Recording requires keyboard: {error}",
    "hotkeys.dependency.native_ready": "Native Windows hotkeys + keyboard recording are available",
    "hotkeys.dependency.keyboard_ready": "keyboard is available",
    "hotkeys.dependency.keyboard_missing": "keyboard is not available: {error}",
    "hotkeys.validation.empty": "The shortcut is empty.",
    "hotkeys.validation.reserved": "{combo} is reserved by the system or too dangerous.",
    "hotkeys.validation.main_key": "A main key is required in addition to ctrl/alt/shift/win.",
    "hotkeys.validation.one_key": "Use only one main key. Example: ctrl+alt+l.",
    "hotkeys.validation.bare_key": "Do not use bare letters/numbers: it would activate while typing.",
    "hotkeys.validation.invasive": "That key alone is too invasive. Add ctrl/alt/shift.",
    "hotkeys.assign.invalid_action": "Invalid action.",
    "hotkeys.assign.saved": "Shortcut saved: {combo}.",
    "hotkeys.assign.replaced": " Replaced {action}.",
    "hotkeys.warning.none_configured": "No hotkeys are configured.",
    "hotkeys.warning.hybrid_fallback.one": "{count} shortcut uses the keyboard fallback; the others use native Windows.",
    "hotkeys.warning.hybrid_fallback.other": "{count} shortcuts use the keyboard fallback; the others use native Windows.",
    "hotkeys.warning.keyboard_fallback": "Keyboard fallback is active; Windows could not reserve the shortcuts.",
    "hotkeys.error.action_not_found": "Action not found: {action_id}",
    "hotkeys.error.action_no_payload": "Action has no payload: {action_id}",
    "hotkeys.error.recording_unavailable": "Recording unavailable: install/enable keyboard. Global hotkeys can still work with native Windows. Details: {error}",
    "hotkeys.error.already_used": "already in use by another application",
    "hotkeys.error.windows_denied": "Windows denied registration",
    "hotkeys.error.native_unsupported": "not supported by the native backend",
    "hotkeys.error.registration_default": "Could not register",
    "hotkeys.error.registration_failed": "Hotkeys could not be registered.",
    "hotkeys.error.registration_detail.one": "{count} shortcut could not be registered. {details}.",
    "hotkeys.error.registration_detail.other": "{count} shortcuts could not be registered. {details}.",
    "hotkeys.error.more": "and {count} more",
    "tray.turn_on": "Turn on",
    "tray.turn_off": "Turn off",
    "tray.toggle": "Toggle",
    "tray.brightness": "Brightness",
    "tray.colors_white": "Colors / white",
    "tray.wiz_scenes": "WiZ scenes",
    "tray.favorites": "Favorites",
    "tray.routines": "Routines",
    "tray.target": "Target",
    "tray.toggle_app": "Toggle WizZ",
    "tray.update_menu": "Refresh menu",
    "tray.reregister_hotkeys": "Re-register hotkeys",
    "tray.hotkeys_status": "Hotkeys: {status}",
    "tray.no_status": "no status",
    "tray.default_favorite": "Favorite {index}",
    "tray.default_routine": "Routine",
    "tray.default_light": "Light",
    "tray.power_on": "on",
    "tray.power_off": "off",
    "tray.connection_online": "online",
    "tray.connection_no_response": "no response",
    "tray.status": "{name}: {power}{brightness} · {connection}",
    "tray.target_status": "Target: {mode} · {ip}",
    "tray.one_light": "1 light",
    "tray.all": "all",
    "tray.sync_window_error": "Could not synchronize the window",
    "tray.hide_window_error": "Could not hide the window",
    "tray.close_window_error": "Could not close the application",
})

# v1.1 Home and Color Studio
CATALOG.update({'color.name.blue': 'Blue', 'color.name.cyan': 'Cyan', 'color.name.green': 'Green', 'color.name.lime': 'Lime', 'color.name.magenta': 'Magenta', 'color.name.orange': 'Orange', 'color.name.pink': 'Pink', 'color.name.red': 'Red', 'color.name.sky': 'Sky blue', 'color.name.violet': 'Violet', 'color.name.yellow': 'Yellow', 'color_studio.applied': 'Applied', 'color_studio.apply_error': 'Could not apply: {error}', 'color_studio.apply_section': 'APPLICATION', 'color_studio.apply_subtitle': 'Immediate delivery with safe throttling', 'color_studio.brightness_subtitle': 'Real light dimming', 'color_studio.brightness_value': 'Brightness {value}%', 'color_studio.cct_section': 'CCT WHITES', 'color_studio.cct_subtitle': 'Real WiZ temperature, independent from RGB', 'color_studio.detected_range': 'Detected range: {minimum}K – {maximum}K', 'color_studio.direct_rgb': 'Direct RGB · separate brightness', 'color_studio.exact_note': 'Exact RGB preserved ({value}%). Using the palette returns to the perceptual model with separate brightness.', 'color_studio.exact_preserved': 'Exact RGB preserved', 'color_studio.favorite_default': 'Favorite', 'color_studio.favorites_empty': 'Save the current color to create quick shortcuts.', 'color_studio.favorites_section': 'QUICK FAVORITES', 'color_studio.favorites_subtitle': 'Saved shortcuts in WizZ', 'color_studio.hue_purity': 'H {hue}° · Purity {purity}% · Brightness {brightness}%', 'color_studio.hue_saturation': 'H {hue}° · S {saturation}% · Exact RGB', 'color_studio.live': 'Live', 'color_studio.live_hint': 'Visual changes are sent with throttling; dragging does not flood the LAN.', 'color_studio.mode_white': 'WHITE', 'color_studio.no_pending_changes': 'No pending changes.', 'color_studio.palette_hint': '↑ white / pastel   ·   ↓ pure color', 'color_studio.palette_note': 'The palette generates direct RGB with perceptual purity; use Brightness for intensity.', 'color_studio.palette_section': 'HUE / PURITY PALETTE', 'color_studio.palette_subtitle': 'Horizontal: hue · vertical: perceptual purity · no black', 'color_studio.pending_changes': 'Pending changes', 'color_studio.precise_section': 'PRECISE CONTROL', 'color_studio.precise_subtitle': 'Exact RGB is preserved until the palette is used again', 'color_studio.quick_subtitle': 'Clean colors at 100%', 'color_studio.recent_section': 'RECENT', 'color_studio.recent_subtitle': 'Last applied colors and whites', 'color_studio.recents_empty': 'No recent colors yet. Apply one to save it here.', 'color_studio.save_current': 'Save current', 'color_studio.subtitle': 'Pure color, Kelvin whites and independent brightness', 'color_studio.use_values': 'Use values', 'color_studio.view_all': 'View all', 'color_studio.white_value': 'White {kelvin}K', 'home.brightness_section': 'BRIGHTNESS', 'home.favorites_empty': 'Save colors or whites from Color Studio or Favorites.', 'home.favorites_section': 'FAVORITES', 'home.header.subtitle': 'Main lighting controls', 'home.header.title': 'Home', 'home.manage': 'Manage', 'home.master': 'Master control', 'home.master_hint': 'Select to toggle the active target', 'home.off': 'OFF', 'home.on': 'ON', 'home.quick.cinema': 'TV / Cinema', 'home.quick.cool': 'Cool', 'home.quick.party': 'Party', 'home.quick.reading': 'Reading', 'home.quick.relax': 'Relax', 'home.quick.reset': 'Reset', 'home.quick.warm': 'Warm', 'home.quick_section': 'QUICK ACTIONS', 'home.refresh_state': 'Refresh real device state', 'home.reset_brightness': 'Restore brightness to 100%', 'home.searching': 'Searching…', 'home.status.no_target': 'No active light', 'home.status.offline': 'Offline', 'home.status.online': 'Online', 'white.name.candle': 'Candle', 'white.name.cool': 'Cool', 'white.name.daylight': 'Daylight', 'white.name.home': 'Home', 'white.name.neutral': 'Neutral', 'white.name.warm': 'Warm', 'white.note.daily': 'daily', 'white.note.energy': 'energy', 'white.note.focus': 'focus', 'white.note.relax': 'relax', 'white.note.soft': 'soft', 'white.note.very_warm': 'very warm'})
