from __future__ import annotations

CATALOG: dict[str, str] = {
    # Aplicación / navegación
    "app.name": "WizZ Desktop",
    "nav.home": "Inicio",
    "nav.color": "Color",
    "nav.scenes": "Escenas",
    "nav.favorites": "Favoritos",
    "nav.routines": "Rutinas",
    "nav.settings": "Ajustes",
    "nav.hotkeys": "Hotkeys",

    # Acciones y estados comunes
    "common.apply": "Aplicar",
    "common.cancel": "Cancelar",
    "common.save": "Guardar",
    "common.close": "Cerrar",
    "common.open": "Abrir",
    "common.add": "Agregar",
    "common.remove": "Quitar",
    "common.rename": "Renombrar",
    "common.edit": "Editar",
    "common.delete": "Eliminar",
    "common.search": "Buscar",
    "common.refresh": "Actualizar",
    "common.settings": "Ajustes",
    "common.on": "Encendida",
    "common.off": "Apagada",
    "common.online": "En línea",
    "common.offline": "Sin conexión",
    "common.enabled": "Activado",
    "common.disabled": "Desactivado",
    "common.none": "Ninguno",
    "common.system_default": "Predeterminado del sistema",
    "common.ready": "Listo",
    "common.error": "Error",

    # Preferencias de idioma
    "language.section": "IDIOMA",
    "language.title": "Idioma de la aplicación",
    "language.description": "Elige el idioma de la interfaz y del menú de bandeja.",
    "language.system": "Predeterminado del sistema",
    "language.english": "Inglés",
    "language.spanish": "Español",
    "language.changed": "Idioma cambiado a {language}.",
    "language.restart_not_required": "La interfaz se actualiza sin reiniciar WizZ Desktop.",

    # Ampolletas / discovery
    "bulbs.section": "AMPOLLETAS",
    "bulbs.search": "Buscar ampolletas",
    "bulbs.searching": "Buscando ampolletas WiZ en la red local…",
    "bulbs.search_done.one": "Búsqueda lista · {count} ampolleta disponible.",
    "bulbs.search_done.other": "Búsqueda lista · {count} ampolletas disponibles.",
    "bulbs.search_error": "Búsqueda finalizada con error: {error}",
    "bulbs.search_not_started": "No se pudo iniciar la búsqueda todavía.",
    "bulbs.none": "No hay ampolletas. Pulsa «Buscar».",
    "bulbs.add_by_ip": "Agregar por IP",
    "bulbs.ip_address": "Dirección IP",
    "bulbs.active": "Ampolleta activa",
    "bulbs.use_as_active": "Usar como activa",
    "bulbs.all": "Todas las detectadas",
    "bulbs.single": "Una ampolleta",
    "bulbs.rename": "Renombrar ampolleta",
    "bulbs.remove": "Quitar ampolleta",
    "bulbs.removed": "Ampolleta quitada. «Buscar ampolletas» puede detectarla nuevamente.",
    "bulbs.already_removed": "La ampolleta ya no estaba registrada.",
    "bulbs.no_mac": "sin MAC",
    "bulbs.no_response": "Sin respuesta",
    "bulbs.info": "Información de ampolleta",

    # Inicio / estado de luz
    "home.title": "Control de iluminación",
    "home.subtitle": "Control WiZ local mediante tu red LAN",
    "light.turn_on": "Encender",
    "light.turn_off": "Apagar",
    "light.toggle": "Alternar",
    "light.brightness": "Brillo",
    "light.color": "Color",
    "light.white": "Blanco",
    "light.temperature": "Temperatura de color",

    # Color Studio
    "color_studio.title": "Color Studio",
    "color_studio.color": "Color",
    "color_studio.white": "Blanco",
    "color_studio.precise": "Preciso",
    "color_studio.live_apply": "Aplicar en vivo",
    "color_studio.pending": "Pendiente",
    "color_studio.hue": "Matiz",
    "color_studio.purity": "Pureza",
    "color_studio.recent": "Colores recientes",
    "color_studio.quick_colors": "Colores rápidos",
    "color_studio.warm": "Cálido",
    "color_studio.neutral": "Neutro",
    "color_studio.cool": "Frío",

    # Favoritos / rutinas / hotkeys
    "favorites.title": "Favoritos",
    "favorites.subtitle": "Colores, blancos, escenas y brillo guardados",

    "favorites.new": "Nuevo",
    "favorites.edit": "Editar",
    "favorites.delete": "Borrar",

    "favorites.empty": "Aún no hay favoritos.",

    "favorites.name": "Nombre",
    "favorites.type": "Tipo",
    "favorites.hex": "HEX",

    "favorites.hue": "Matiz",
    "favorites.saturation": "Intensidad",
    "favorites.lightness": "Claridad",

    "favorites.scene": "Escena",
    "favorites.wiz_scene": "Escena WiZ",
    "favorites.speed_value": "Velocidad {value}",
    "favorites.brightness_value": "Brillo {value}%",
    "favorites.scene_summary": "{scene} · velocidad {speed}",

    "favorites.cancel": "Cancelar",
    "favorites.save": "Guardar",

    "favorites.new_title": "Nuevo favorito",
    "favorites.edit_title": "Editar favorito",

    "favorites.default_name": "Nuevo favorito",
    "routines.title": "Rutinas",
    "routines.empty": "Todavía no hay rutinas.",
    "hotkeys.title": "Hotkeys globales",
    "hotkeys.description": "Controla WizZ Desktop mientras otra aplicación tiene el foco.",

    # Bandeja
    "tray.show_app": "Abrir WizZ Desktop",
    "tray.hide_app": "Ocultar WizZ Desktop",
    "tray.quick_panel": "Panel rápido",
    "tray.settings": "Ajustes",
    "tray.exit": "Salir",
    "tray.no_light": "Sin ampolleta activa",
    "tray.all_lights": "Todas las ampolletas",

    # Panel rápido
    "quick.title": "Panel rápido",
    "quick.open_full": "Abrir WizZ Desktop",
    "quick.open_settings": "Abrir Ajustes",
    "quick.no_connection": "Sin conexión",
    "quick.no_active_light": "Sin ampolleta activa",
    "quick.favorites": "Favoritos",
    "quick.whites": "Blancos",
    "quick.colors": "Colores",
    "quick.press_escape": "Pulsa Esc para cerrar",

    # Escritorio/runtime
    "runtime.background": "INICIO Y SEGUNDO PLANO",
    "runtime.tray_enabled": "Bandeja activa",
    "runtime.close_to_tray": "Cerrar a bandeja",
    "runtime.open_minimized": "Abrir minimizado",
    "runtime.start_with_windows": "Iniciar con Windows",
    "runtime.saved": "Configuración de segundo plano guardada.",

    # Acerca de
    "about.title": "ACERCA DE",
    "about.local_control": "Control WiZ local · sin nube obligatoria",
    "about.data": "Datos",
    "about.logs": "Logs",


    # Settings language integration
    'language.selector': 'Idioma / Language',
    'language.effective': 'Idioma efectivo: {language}',
    'language.detected': 'Idioma de Windows: {language}',
    'settings.title': 'Ajustes',
    'settings.subtitle': 'Destino, discovery y gestión de ampolletas',
    'settings.target.section': 'DESTINO',
    'settings.target.mode': 'Modo de control',
    'settings.target.help': 'El destino solo determina a qué IP se envían los comandos.',
    'settings.slider_performance': 'Rendimiento de sliders',
    'settings.slider.35': '35 ms · ultra rápido / más CPU',
    'settings.slider.65': '65 ms · recomendado',
    'settings.slider.90': '90 ms · suave / menos CPU',
    'settings.slider.130': '130 ms · ahorro de CPU',
    'settings.cleanup_offline': 'Limpiar offline',
    'settings.cleanup_title': 'Limpieza lista',
    'settings.cleanup_result': 'Se quitaron {count} IP offline.',
    'runtime.tray_enabled.description': 'Mantiene WizZ disponible junto al reloj.',
    'runtime.close_to_tray.description': 'La X oculta la ventana en vez de salir.',
    'runtime.open_minimized.description': 'Inicia oculto cuando la bandeja está activa.',
    'runtime.start_with_windows.description': 'Registra o quita el inicio automático.',
    'runtime.restart_hint': 'Los cambios de bandeja se aplican mejor al reiniciar la app. El modo desarrollo no fuerza restaurar ventanas.',
    'about.storage_hint': 'En la app empaquetada, configuraciones y logs viven en el almacenamiento persistente y se conservan entre actualizaciones.',
    'common.information': 'Información',
    'common.name': 'Nombre',
    'common.ok': 'OK',
    'bulbs.mode.single': 'Una ampolleta',
    'bulbs.mode.all': 'Todas las detectadas',
    'bulbs.status.online': '● en línea · {label}{kelvin}',
    'bulbs.status.offline': '○ sin respuesta',
    'bulbs.cleanup_removed.one': 'Se quitó {count} IP offline.',
    'bulbs.cleanup_removed.other': 'Se quitaron {count} IP offline.',
    'bulbs.rename_title': 'Renombrar ampolleta',
    'bulbs.add_title': 'Agregar por IP',
    'bulbs.active_badge': 'ACTIVA',
    'bulbs.target_badge': 'TARGET',
    'about.product_subtitle': 'Control WiZ local · sin nube obligatoria',
}

# Interfaz completa de la aplicación
CATALOG.update({
    "common.yes": "Sí",
    "common.no": "No",
    "common.type": "Tipo",
    "common.value": "Valor",
    "common.description": "Descripción",
    "common.icon": "Icono",
    "common.actions": "ACCIONES",
    "common.duplicate": "Duplicar",
    "common.move_up": "Subir",
    "common.move_down": "Bajar",
    "common.test": "Probar",
    "common.record": "Grabar",
    "common.export": "Exportar",
    "common.restore_defaults": "Restaurar predeterminados",
    "common.status": "ESTADO",
    "common.percent_value": "{value}%",
    "common.kelvin_value": "{value}K",
    "color_studio.preset_tooltip": "{name} · {value}",
    "color_studio.white_detail": "{name} · Brillo {brightness}%",
    "color_studio.hue_purity_short": "H {hue}° · Pureza {purity}%",
    "color_studio.cct_detail": "{kelvin}K · {name}",
    "home.status.active": "{active}/{count} en línea{extra}",
    "home.status.saved.one": "{count} guardada · sin respuesta",
    "home.status.saved.other": "{count} guardadas · sin respuesta",
    "home.status.no_bulbs": "Sin ampolletas",
    "home.target_summary": "destino: {mode} · {ip}",
    "home.capabilities.rgb_white": "RGB + Blancos",
    "home.capabilities.white": "Blancos",
    "home.capabilities.none": "Sin capacidades",
    "settings.open_folder_error": "No se pudo abrir la carpeta: {error}",
    "settings.info.name": "Nombre",
    "settings.info.online": "En línea",
    "settings.info.active": "Activa",
    "settings.info.target": "Destino",
    "settings.info.module": "Módulo",
    "settings.info.firmware": "Firmware",
    "settings.info.state": "Estado",
    "settings.info.brightness": "Brillo",
    "settings.info.temperature": "Temperatura",
    "settings.info.scene": "Escena",
    "settings.info.whites": "Blancos",
    "settings.info.power_meter": "Medidor W",
    "settings.info.model": "Modelo",
    "bulbs.target_badge": "DESTINO",
    "bulbs.online_detail": "● en línea · {label}{range}",
    "bulbs.offline_detail": "○ sin respuesta",
    "bulbs.ip_example": "192.168.1.20",
    "runtime.startup.windows_only": "Inicio con Windows solo está disponible en Windows.",
    "runtime.startup.update_error": "No se pudo modificar Inicio con Windows: {error}",
    "runtime.startup.updated": "Inicio con Windows actualizado.",
    "runtime.startup.disabled": "Inicio con Windows desactivado.",
    "instance.already_running": "{app} ya se está ejecutando. Revisa el área de notificación de Windows.",

    "scenes.title": "Escenas",
    "scenes.subtitle": "Escenas WiZ y escenas personalizadas locales",
    "scenes.save_current": "Guardar actual",
    "scenes.new": "Nueva escena",
    "scenes.my_section": "MIS ESCENAS",
    "scenes.wiz_section": "ESCENAS WIZ",
    "scenes.speed_section": "VELOCIDAD DE ESCENA",
    "scenes.reset_speed": "Restaurar velocidad",
    "scenes.empty": "Aún no tienes escenas personalizadas.",
    "scenes.dynamic": "dinámica",
    "scenes.static": "estática",
    "scenes.custom_fallback": "Mi escena",
    "scenes.custom_type": "personalizada",
    "scenes.scene_summary": "Escena {scene_id} · velocidad {speed}",
    "scenes.capture_default_name": "Escena actual",
    "scenes.capture_title": "Guardar estado actual",
    "scenes.type_rgb": "Color HEX",
    "scenes.type_white": "Blanco Kelvin",
    "scenes.type_wiz": "Escena WiZ",
    "scenes.edit_title": "Editar escena",
    "scenes.new_title": "Nueva escena personalizada",
    "scenes.dynamic_speed": "Velocidad si es escena dinámica",
    "scene.group.favorites": "Favoritas",
    "scene.group.nature": "Naturaleza",
    "scene.group.ambience": "Ambiente",
    "scene.group.whites": "Blancos",
    "scene.group.routines": "Rutinas",
    "scene.group.holidays": "Festividades",
    "scene.name.1": "Océano",
    "scene.name.2": "Romance",
    "scene.name.3": "Atardecer",
    "scene.name.4": "Fiesta",
    "scene.name.5": "Chimenea",
    "scene.name.6": "Acogedor",
    "scene.name.7": "Bosque",
    "scene.name.8": "Pastel",
    "scene.name.9": "Despertar",
    "scene.name.10": "Dormir",
    "scene.name.11": "Blanco Cálido",
    "scene.name.12": "Luz de Día",
    "scene.name.13": "Blanco Frío",
    "scene.name.14": "Luz Nocturna",
    "scene.name.15": "Concentración",
    "scene.name.16": "Relax",
    "scene.name.17": "Colores Reales",
    "scene.name.18": "TV / Cine",
    "scene.name.19": "Plantas",
    "scene.name.20": "Primavera",
    "scene.name.21": "Verano",
    "scene.name.22": "Otoño",
    "scene.name.23": "Inmersión",
    "scene.name.24": "Jungla",
    "scene.name.25": "Mojito",
    "scene.name.26": "Club",
    "scene.name.27": "Navidad",
    "scene.name.28": "Halloween",
    "scene.name.29": "Vela",
    "scene.name.30": "Dorado",
    "scene.name.31": "Pulso",
    "scene.name.32": "Steampunk",
    "scene.name.33": "Diwali",
})

CATALOG.update({
    "routines.subtitle": "Presets compuestos simples para hotkeys y acciones rápidas",
    "routines.new": "Nueva",
    "routines.capture_state": "Capturar estado",
    "routines.info": "Crea rutinas visuales sin JSON: color, blanco, brillo, escena, favoritos, espera y destino.",
    "routines.restore_presets": "Restaurar presets",
    "routines.empty_full": "No hay rutinas.",
    "routines.fallback_name": "Rutina",
    "routines.default_name": "Nueva rutina",
    "routines.no_actions": "Sin acciones",
    "routines.apply": "Aplicar",
    "routines.capture_name": "Rutina capturada",
    "routines.capture_description": "Creada desde el estado actual",
    "routines.field.card_color": "Color tarjeta",
    "routines.add_action": "Agregar acción",
    "routines.new_title": "Nueva rutina",
    "routines.edit_title": "Editar rutina",
    "routines.action.edit": "Editar acción",
    "routines.action.delete": "Borrar acción",
    "routines.action.label": "Acción",
    "routines.action.no_config": "Esta acción no necesita configuración.",
    "routines.action.add_title": "Agregar acción",
    "routines.action.edit_title": "Editar acción",
    "routines.action.save": "Guardar acción",
    "routines.action.no_value": "sin valor",
    "routines.action.not_found": "No encontrado",
    "routines.action.turn_on": "Encender",
    "routines.action.turn_off": "Apagar",
    "routines.action.toggle": "Alternar",
    "routines.action.brightness": "Brillo",
    "routines.action.brightness_delta": "Brillo +/-",
    "routines.action.rgb": "Color",
    "routines.action.white_percent": "Blanco cálido/frío",
    "routines.action.white_kelvin": "Blanco Kelvin",
    "routines.action.scene": "Escena WiZ",
    "routines.action.favorite": "Favorito",
    "routines.action.custom_scene": "Escena personalizada",
    "routines.action.routine": "Otra rutina",
    "routines.action.wait": "Esperar",
    "routines.action.target_mode": "Destino",
    "routines.action.brightness_value": "Brillo {value}%",
    "routines.action.delta_value": "Cambio {value:+d}%",
    "routines.action.white_value": "Blanco {percent}% · {kelvin}K",
    "routines.action.speed_value": "Velocidad {value}",
    "routines.action.wait_value": "Esperar {value}ms",
    "routines.action.favorite_empty": "No hay favoritos creados.",
    "routines.action.custom_scene_empty": "No hay escenas personalizadas.",
    "routines.action.routine_empty": "No hay otras rutinas disponibles.",
    "routines.target.single": "Una ampolleta",
    "routines.target.all": "Todas",
    "routines.icon.auto": "Auto",
    "routines.icon.study": "Estudio",
    "routines.icon.night": "Noche",
    "routines.icon.gaming": "Juego",
    "routines.icon.cinema": "Cine",
    "routines.icon.reading": "Lectura",
    "routines.icon.power_off": "Apagado",
    "routines.icon.color": "Color",
    "routines.icon.light": "Luz",
    "routines.icon.routine": "Rutina",
    "routines.copy_suffix": "copia",
    "routine.default.study.name": "Modo estudio",
    "routine.default.study.description": "Blanco claro y brillo alto para trabajar.",
    "routine.default.night.name": "Modo noche",
    "routine.default.night.description": "Cálido y bajo brillo.",
    "routine.default.gaming.name": "Modo juego",
    "routine.default.gaming.description": "Azul/morado con brillo medio.",
    "routine.default.cinema.name": "Modo cine",
    "routine.default.cinema.description": "Escena TV/Cine con brillo reducido.",
    "routine.default.reading.name": "Modo lectura",
    "routine.default.reading.description": "Blanco neutro cómodo.",
    "routine.default.soft_off.name": "Apagado suave",
    "routine.default.soft_off.description": "Baja brillo un instante y apaga.",
})

CATALOG.update({
    "hotkeys.subtitle": "Atajos globales para luz, rutinas y favoritos",
    "hotkeys.reregister": "Re-registrar",
    "hotkeys.enabled": "Hotkeys activas",
    "hotkeys.enabled_help": "Servicio global de la app.",
    "hotkeys.suppress": "Capturar teclas",
    "hotkeys.suppress_help": "Solo para el fallback keyboard.",
    "hotkeys.release": "Ejecutar al soltar",
    "hotkeys.release_help": "Keyboard; Windows usa antirebote.",
    "hotkeys.debounce": "Antirebote",
    "hotkeys.category": "Categoría",
    "hotkeys.search_action": "Buscar acción",
    "hotkeys.search_hint": "cine, rojo, noche, brillo...",
    "hotkeys.action": "Acción",
    "hotkeys.shortcut": "Atajo",
    "hotkeys.shortcut_hint": "ctrl+alt+l",
    "hotkeys.create_section": "CREAR / EDITAR ATAJO",
    "hotkeys.create_help": "Elige una acción, graba la combinación y guarda. Los conflictos se reemplazan con aviso.",
    "hotkeys.templates_section": "PLANTILLAS ÚTILES",
    "hotkeys.assigned_section": "ATAJOS CONFIGURADOS",
    "hotkeys.custom_color": "Color personalizado",
    "hotkeys.quick_colors": "Colores rápidos",
    "hotkeys.hue": "Tono",
    "hotkeys.intensity": "Intensidad",
    "hotkeys.lightness": "Claridad",
    "hotkeys.unavailable": "no disponible",
    "hotkeys.choose_shortcut": "Elige o graba un atajo. Recomendado: ctrl+alt+letra/flecha.",
    "hotkeys.conflict": "Conflicto: reemplazará '{action}'.",
    "hotkeys.valid": "Atajo válido.",
    "hotkeys.empty": "No hay hotkeys asignadas.",
    "hotkeys.recording": "Presiona teclas...",
    "hotkeys.recording_help": "Grabando. Presiona ESC para cancelar.",
    "hotkeys.export_title": "Hotkeys JSON",
    "hotkeys.ms_value": "{value} ms",
    "hotkeys.group.general": "General",
    "hotkeys.group.target": "Destino",
    "hotkeys.group.brightness": "Brillo",
    "hotkeys.group.whites": "Blancos",
    "hotkeys.group.colors": "Colores",
    "hotkeys.group.custom_colors": "Colores personalizados",
    "hotkeys.group.wiz_scenes": "Escenas WiZ",
    "hotkeys.group.favorites": "Favoritos",
    "hotkeys.group.my_scenes": "Mis escenas",
    "hotkeys.group.routines": "Rutinas",
    "hotkeys.group.custom": "Personalizado",
    "hotkeys.action.toggle": "Alternar encendido",
    "hotkeys.action.on": "Encender",
    "hotkeys.action.off": "Apagar",
    "hotkeys.action.reset": "Restaurar luz",
    "hotkeys.action.target_single": "Modo una ampolleta",
    "hotkeys.action.target_all": "Modo todas",
    "hotkeys.action.bri_up": "Brillo +10%",
    "hotkeys.action.bri_down": "Brillo -10%",
    "hotkeys.action.brightness": "Brillo {value}%",
    "hotkeys.action.white_warm": "Blanco cálido",
    "hotkeys.action.white_neutral": "Blanco neutro",
    "hotkeys.action.white_cold": "Blanco frío",
    "hotkeys.action.white_range": "Blanco {value}% del rango",
    "hotkeys.action.color_custom": "Color personalizado",
    "hotkeys.action.color_hex": "Color #{value}",
    "hotkeys.preset.toggle": "Alternar",
    "hotkeys.preset.bri_up": "Brillo +",
    "hotkeys.preset.bri_down": "Brillo -",
    "hotkeys.preset.red": "Rojo",
    "hotkeys.preset.cinema": "Cine",
    "hotkeys.preset.night": "Modo noche",
})

CATALOG.update({
    "hotkeys.status.disabled": "desactivado",
    "hotkeys.status.native": "Windows nativo activo{suffix}",
    "hotkeys.status.hybrid": "Windows + fallback activo{suffix}",
    "hotkeys.status.keyboard": "teclado global activo{suffix}",
    "hotkeys.status.unregistered": "sin registrar",
    "hotkeys.status.empty": "sin atajos",
    "hotkeys.dependency.native_recording_missing": "Hotkeys nativos de Windows disponibles. La grabación requiere keyboard: {error}",
    "hotkeys.dependency.native_ready": "Hotkeys nativos de Windows + grabación con keyboard disponibles",
    "hotkeys.dependency.keyboard_ready": "keyboard disponible",
    "hotkeys.dependency.keyboard_missing": "keyboard no disponible: {error}",
    "hotkeys.validation.empty": "El atajo está vacío.",
    "hotkeys.validation.reserved": "{combo} está reservado por el sistema o es demasiado peligroso.",
    "hotkeys.validation.main_key": "Falta una tecla principal además de ctrl/alt/shift/win.",
    "hotkeys.validation.one_key": "Usa solo una tecla principal. Ejemplo: ctrl+alt+l.",
    "hotkeys.validation.bare_key": "No uses letras/números solos: se activaría al escribir.",
    "hotkeys.validation.invasive": "Esa tecla sola es demasiado invasiva. Agrega ctrl/alt/shift.",
    "hotkeys.assign.invalid_action": "Acción inválida.",
    "hotkeys.assign.saved": "Atajo guardado: {combo}.",
    "hotkeys.assign.replaced": " Reemplazó {action}.",
    "hotkeys.warning.none_configured": "No hay hotkeys configurados.",
    "hotkeys.warning.hybrid_fallback.one": "{count} atajo usa el fallback keyboard; los demás usan Windows nativo.",
    "hotkeys.warning.hybrid_fallback.other": "{count} atajos usan el fallback keyboard; los demás usan Windows nativo.",
    "hotkeys.warning.keyboard_fallback": "Fallback keyboard activo; Windows no pudo reservar las combinaciones.",
    "hotkeys.error.action_not_found": "Acción no encontrada: {action_id}",
    "hotkeys.error.action_no_payload": "Acción sin payload: {action_id}",
    "hotkeys.error.recording_unavailable": "Grabación no disponible: instala/habilita keyboard. Los hotkeys globales pueden seguir funcionando con Windows nativo. Detalle: {error}",
    "hotkeys.error.already_used": "ya está en uso por otra aplicación",
    "hotkeys.error.windows_denied": "Windows rechazó el registro",
    "hotkeys.error.native_unsupported": "no es compatible con el backend nativo",
    "hotkeys.error.registration_default": "No se pudo registrar",
    "hotkeys.error.registration_failed": "No se pudieron registrar los hotkeys.",
    "hotkeys.error.registration_detail.one": "No se pudo registrar {count} atajo. {details}.",
    "hotkeys.error.registration_detail.other": "No se pudieron registrar {count} atajos. {details}.",
    "hotkeys.error.more": "y {count} más",
    "tray.turn_on": "Encender",
    "tray.turn_off": "Apagar",
    "tray.toggle": "Alternar",
    "tray.brightness": "Brillo",
    "tray.colors_white": "Colores / blancos",
    "tray.wiz_scenes": "Escenas WiZ",
    "tray.favorites": "Favoritos",
    "tray.routines": "Rutinas",
    "tray.target": "Target",
    "tray.toggle_app": "Alternar WizZ",
    "tray.update_menu": "Actualizar menú",
    "tray.reregister_hotkeys": "Re-registrar hotkeys",
    "tray.hotkeys_status": "Hotkeys: {status}",
    "tray.no_status": "sin estado",
    "tray.default_favorite": "Favorito {index}",
    "tray.default_routine": "Rutina",
    "tray.default_light": "Ampolleta",
    "tray.power_on": "encendida",
    "tray.power_off": "apagada",
    "tray.connection_online": "en línea",
    "tray.connection_no_response": "sin respuesta",
    "tray.status": "{name}: {power}{brightness} · {connection}",
    "tray.target_status": "Target: {mode} · {ip}",
    "tray.one_light": "1 luz",
    "tray.all": "todas",
    "tray.sync_window_error": "No se pudo sincronizar la ventana",
    "tray.hide_window_error": "No se pudo ocultar la ventana",
    "tray.close_window_error": "No se pudo cerrar la aplicación",
})

# v1.1 Home and Color Studio
CATALOG.update({'color.name.blue': 'Azul', 'color.name.cyan': 'Cian', 'color.name.green': 'Verde', 'color.name.lime': 'Lima', 'color.name.magenta': 'Magenta', 'color.name.orange': 'Naranjo', 'color.name.pink': 'Rosa', 'color.name.red': 'Rojo', 'color.name.sky': 'Celeste', 'color.name.violet': 'Violeta', 'color.name.yellow': 'Amarillo', 'color_studio.applied': 'Aplicado', 'color_studio.apply_error': 'No se pudo aplicar: {error}', 'color_studio.apply_section': 'APLICACIÓN', 'color_studio.apply_subtitle': 'Envío inmediato con throttle seguro', 'color_studio.brightness_subtitle': 'Dimming real de la ampolleta', 'color_studio.brightness_value': 'Brillo {value}%', 'color_studio.cct_section': 'BLANCOS CCT', 'color_studio.cct_subtitle': 'Temperatura real WiZ, independiente del RGB', 'color_studio.detected_range': 'Rango detectado: {minimum}K – {maximum}K', 'color_studio.direct_rgb': 'RGB directo · brillo separado', 'color_studio.exact_note': 'RGB exacto conservado ({value}%). Al tocar la paleta volverá al modelo perceptual con brillo separado.', 'color_studio.exact_preserved': 'RGB exacto preservado', 'color_studio.favorite_default': 'Favorito', 'color_studio.favorites_empty': 'Guarda el color actual para crear accesos rápidos.', 'color_studio.favorites_section': 'FAVORITOS RÁPIDOS', 'color_studio.favorites_subtitle': 'Accesos guardados en WizZ', 'color_studio.hue_purity': 'H {hue}° · Pureza {purity}% · Brillo {brightness}%', 'color_studio.hue_saturation': 'H {hue}° · S {saturation}% · RGB exacto', 'color_studio.live': 'En vivo', 'color_studio.live_hint': 'Los cambios visuales se envían con throttle; el drag no satura la LAN.', 'color_studio.mode_white': 'BLANCO', 'color_studio.no_pending_changes': 'No hay cambios pendientes.', 'color_studio.palette_hint': '↑ blanco / pastel   ·   ↓ color puro', 'color_studio.palette_note': 'La paleta genera RGB directo con pureza perceptual; usa Brillo para la intensidad.', 'color_studio.palette_section': 'PALETA HUE / PUREZA', 'color_studio.palette_subtitle': 'Horizontal: matiz · vertical: pureza perceptual · sin negro', 'color_studio.pending_changes': 'Cambios pendientes', 'color_studio.precise_section': 'CONTROL PRECISO', 'color_studio.precise_subtitle': 'RGB exacto se conserva hasta volver a tocar la paleta', 'color_studio.quick_subtitle': 'Colores limpios al 100%', 'color_studio.recent_section': 'RECIENTES', 'color_studio.recent_subtitle': 'Últimos colores y blancos aplicados', 'color_studio.recents_empty': 'Aún no hay colores recientes. Aplica uno para guardarlo aquí.', 'color_studio.save_current': 'Guardar actual', 'color_studio.subtitle': 'Color puro, blancos Kelvin y brillo independiente', 'color_studio.use_values': 'Usar valores', 'color_studio.view_all': 'Ver todos', 'color_studio.white_value': 'Blanco {kelvin}K', 'home.brightness_section': 'BRILLO', 'home.favorites_empty': 'Guarda colores o blancos desde Color Studio o Favoritos.', 'home.favorites_section': 'FAVORITOS', 'home.header.subtitle': 'Control principal de iluminación', 'home.header.title': 'Inicio', 'home.manage': 'Administrar', 'home.master': 'Control maestro', 'home.master_hint': 'Toca para alternar el target activo', 'home.off': 'APAGADO', 'home.on': 'ENCENDIDO', 'home.quick.cinema': 'TV / Cine', 'home.quick.cool': 'Frío', 'home.quick.party': 'Fiesta', 'home.quick.reading': 'Lectura', 'home.quick.relax': 'Relax', 'home.quick.reset': 'Reset', 'home.quick.warm': 'Cálido', 'home.quick_section': 'ACCESOS RÁPIDOS', 'home.refresh_state': 'Releer estado real', 'home.reset_brightness': 'Restaurar brillo a 100%', 'home.searching': 'Buscando…', 'home.status.no_target': 'Sin ampolleta activa', 'home.status.offline': 'Sin conexión', 'home.status.online': 'En línea', 'white.name.candle': 'Vela', 'white.name.cool': 'Frío', 'white.name.daylight': 'Día', 'white.name.home': 'Hogar', 'white.name.neutral': 'Neutro', 'white.name.warm': 'Cálido', 'white.note.daily': 'diario', 'white.note.energy': 'energía', 'white.note.focus': 'foco', 'white.note.relax': 'relax', 'white.note.soft': 'suave', 'white.note.very_warm': 'muy cálido'})
