from __future__ import annotations

CATALOG: dict[str, str] = {
    # Aplicación / navegación
    "app.name": "WizZ Desktop",
    "nav.home": "Inicio",
    "nav.color": "Color",
    "nav.scenes": "Escenas",
    "nav.favorites": "Favoritos",
    "nav.routines": "Rutinas",
    "nav.settings": "Ajustes",
    "nav.hotkeys": "Hotkeys",

    # Acciones y estados comunes
    "common.apply": "Aplicar",
    "common.cancel": "Cancelar",
    "common.save": "Guardar",
    "common.close": "Cerrar",
    "common.open": "Abrir",
    "common.add": "Agregar",
    "common.remove": "Quitar",
    "common.rename": "Renombrar",
    "common.edit": "Editar",
    "common.delete": "Eliminar",
    "common.search": "Buscar",
    "common.refresh": "Actualizar",
    "common.settings": "Ajustes",
    "common.on": "Encendida",
    "common.off": "Apagada",
    "common.online": "En línea",
    "common.offline": "Sin conexión",
    "common.enabled": "Activado",
    "common.disabled": "Desactivado",
    "common.none": "Ninguno",
    "common.system_default": "Predeterminado del sistema",
    "common.ready": "Listo",
    "common.error": "Error",

    # Preferencias de idioma
    "language.section": "IDIOMA",
    "language.title": "Idioma de la aplicación",
    "language.description": "Elige el idioma de la interfaz y del menú de bandeja.",
    "language.system": "Predeterminado del sistema",
    "language.english": "Inglés",
    "language.spanish": "Español",
    "language.changed": "Idioma cambiado a {language}.",
    "language.restart_not_required": "La interfaz se actualiza sin reiniciar WizZ Desktop.",

    # Ampolletas / discovery
    "bulbs.section": "AMPOLLETAS",
    "bulbs.search": "Buscar ampolletas",
    "bulbs.searching": "Buscando ampolletas WiZ en la red local…",
    "bulbs.search_done.one": "Búsqueda lista · {count} ampolleta disponible.",
    "bulbs.search_done.other": "Búsqueda lista · {count} ampolletas disponibles.",
    "bulbs.search_error": "Búsqueda finalizada con error: {error}",
    "bulbs.search_not_started": "No se pudo iniciar la búsqueda todavía.",
    "bulbs.none": "No hay ampolletas. Pulsa «Buscar».",
    "bulbs.add_by_ip": "Agregar por IP",
    "bulbs.ip_address": "Dirección IP",
    "bulbs.active": "Ampolleta activa",
    "bulbs.use_as_active": "Usar como activa",
    "bulbs.all": "Todas las detectadas",
    "bulbs.single": "Una ampolleta",
    "bulbs.rename": "Renombrar ampolleta",
    "bulbs.remove": "Quitar ampolleta",
    "bulbs.removed": "Ampolleta quitada. «Buscar ampolletas» puede detectarla nuevamente.",
    "bulbs.already_removed": "La ampolleta ya no estaba registrada.",
    "bulbs.no_mac": "sin MAC",
    "bulbs.no_response": "Sin respuesta",
    "bulbs.info": "Información de ampolleta",

    # Inicio / estado de luz
    "home.title": "Control de iluminación",
    "home.subtitle": "Control WiZ local mediante tu red LAN",
    "light.turn_on": "Encender",
    "light.turn_off": "Apagar",
    "light.toggle": "Alternar",
    "light.brightness": "Brillo",
    "light.color": "Color",
    "light.white": "Blanco",
    "light.temperature": "Temperatura de color",

    # Color Studio
    "color_studio.title": "Color Studio",
    "color_studio.color": "Color",
    "color_studio.white": "Blanco",
    "color_studio.precise": "Preciso",
    "color_studio.live_apply": "Aplicar en vivo",
    "color_studio.pending": "Pendiente",
    "color_studio.hue": "Matiz",
    "color_studio.purity": "Pureza",
    "color_studio.recent": "Colores recientes",
    "color_studio.quick_colors": "Colores rápidos",
    "color_studio.warm": "Cálido",
    "color_studio.neutral": "Neutro",
    "color_studio.cool": "Frío",

    # Favoritos / rutinas / hotkeys
    "favorites.title": "Favoritos",
    "favorites.subtitle": "Colores, blancos, escenas y brillo guardados",

    "favorites.new": "Nuevo",
    "favorites.edit": "Editar",
    "favorites.delete": "Borrar",

    "favorites.empty": "Aún no hay favoritos.",

    "favorites.name": "Nombre",
    "favorites.type": "Tipo",
    "favorites.hex": "HEX",

    "favorites.hue": "Matiz",
    "favorites.saturation": "Intensidad",
    "favorites.lightness": "Claridad",

    "favorites.scene": "Escena",
    "favorites.wiz_scene": "Escena WiZ",
    "favorites.speed_value": "Velocidad {value}",
    "favorites.brightness_value": "Brillo {value}%",
    "favorites.scene_summary": "{scene} · velocidad {speed}",

    "favorites.cancel": "Cancelar",
    "favorites.save": "Guardar",

    "favorites.new_title": "Nuevo favorito",
    "favorites.edit_title": "Editar favorito",

    "favorites.default_name": "Nuevo favorito",
    "routines.title": "Rutinas",
    "routines.empty": "Todavía no hay rutinas.",
    "hotkeys.title": "Hotkeys globales",
    "hotkeys.description": "Controla WizZ Desktop mientras otra aplicación tiene el foco.",

    # Bandeja
    "tray.show_app": "Abrir WizZ Desktop",
    "tray.hide_app": "Ocultar WizZ Desktop",
    "tray.quick_panel": "Panel rápido",
    "tray.settings": "Ajustes",
    "tray.exit": "Salir",
    "tray.no_light": "Sin ampolleta activa",
    "tray.all_lights": "Todas las ampolletas",

    # Panel rápido
    "quick.title": "Panel rápido",
    "quick.open_full": "Abrir WizZ Desktop",
    "quick.open_settings": "Abrir Ajustes",
    "quick.no_connection": "Sin conexión",
    "quick.no_active_light": "Sin ampolleta activa",
    "quick.favorites": "Favoritos",
    "quick.whites": "Blancos",
    "quick.colors": "Colores",
    "quick.press_escape": "Pulsa Esc para cerrar",

    # Escritorio/runtime
    "runtime.background": "INICIO Y SEGUNDO PLANO",
    "runtime.tray_enabled": "Bandeja activa",
    "runtime.close_to_tray": "Cerrar a bandeja",
    "runtime.open_minimized": "Abrir minimizado",
    "runtime.start_with_windows": "Iniciar con Windows",
    "runtime.saved": "Configuración de segundo plano guardada.",

    # Acerca de
    "about.title": "ACERCA DE",
    "about.local_control": "Control WiZ local · sin nube obligatoria",
    "about.data": "Datos",
    "about.logs": "Logs",


    # Settings language integration
    'language.selector': 'Idioma / Language',
    'language.effective': 'Idioma efectivo: {language}',
    'language.detected': 'Idioma de Windows: {language}',
    'settings.title': 'Ajustes',
    'settings.subtitle': 'Destino, discovery y gestión de ampolletas',
    'settings.target.section': 'DESTINO',
    'settings.target.mode': 'Modo de control',
    'settings.target.help': 'El destino solo determina a qué IP se envían los comandos.',
    'settings.slider_performance': 'Rendimiento de sliders',
    'settings.slider.35': '35 ms · ultra rápido / más CPU',
    'settings.slider.65': '65 ms · recomendado',
    'settings.slider.90': '90 ms · suave / menos CPU',
    'settings.slider.130': '130 ms · ahorro de CPU',
    'settings.cleanup_offline': 'Limpiar offline',
    'settings.cleanup_title': 'Limpieza lista',
    'settings.cleanup_result': 'Se quitaron {count} IP offline.',
    'runtime.tray_enabled.description': 'Mantiene WizZ disponible junto al reloj.',
    'runtime.close_to_tray.description': 'La X oculta la ventana en vez de salir.',
    'runtime.open_minimized.description': 'Inicia oculto cuando la bandeja está activa.',
    'runtime.start_with_windows.description': 'Registra o quita el inicio automático.',
    'runtime.restart_hint': 'Los cambios de bandeja se aplican mejor al reiniciar la app. El modo desarrollo no fuerza restaurar ventanas.',
    'about.storage_hint': 'En la app empaquetada, configuraciones y logs viven en el almacenamiento persistente y se conservan entre actualizaciones.',
    'common.information': 'Información',
    'common.name': 'Nombre',
    'common.ok': 'OK',
    'bulbs.mode.single': 'Una ampolleta',
    'bulbs.mode.all': 'Todas las detectadas',
    'bulbs.status.online': '● en línea · {label}{kelvin}',
    'bulbs.status.offline': '○ sin respuesta',
    'bulbs.cleanup_removed.one': 'Se quitó {count} IP offline.',
    'bulbs.cleanup_removed.other': 'Se quitaron {count} IP offline.',
    'bulbs.rename_title': 'Renombrar ampolleta',
    'bulbs.add_title': 'Agregar por IP',
    'bulbs.active_badge': 'ACTIVA',
    'bulbs.target_badge': 'TARGET',
    'about.product_subtitle': 'Control WiZ local · sin nube obligatoria',
}

# v1.1 Home and Color Studio
CATALOG.update({'color.name.blue': 'Azul', 'color.name.cyan': 'Cian', 'color.name.green': 'Verde', 'color.name.lime': 'Lima', 'color.name.magenta': 'Magenta', 'color.name.orange': 'Naranjo', 'color.name.pink': 'Rosa', 'color.name.red': 'Rojo', 'color.name.sky': 'Celeste', 'color.name.violet': 'Violeta', 'color.name.yellow': 'Amarillo', 'color_studio.applied': 'Aplicado', 'color_studio.apply_error': 'No se pudo aplicar: {error}', 'color_studio.apply_section': 'APLICACIÓN', 'color_studio.apply_subtitle': 'Envío inmediato con throttle seguro', 'color_studio.brightness_subtitle': 'Dimming real de la ampolleta', 'color_studio.brightness_value': 'Brillo {value}%', 'color_studio.cct_section': 'BLANCOS CCT', 'color_studio.cct_subtitle': 'Temperatura real WiZ, independiente del RGB', 'color_studio.detected_range': 'Rango detectado: {minimum}K – {maximum}K', 'color_studio.direct_rgb': 'RGB directo · brillo separado', 'color_studio.exact_note': 'RGB exacto conservado ({value}%). Al tocar la paleta volverá al modelo perceptual con brillo separado.', 'color_studio.exact_preserved': 'RGB exacto preservado', 'color_studio.favorite_default': 'Favorito', 'color_studio.favorites_empty': 'Guarda el color actual para crear accesos rápidos.', 'color_studio.favorites_section': 'FAVORITOS RÁPIDOS', 'color_studio.favorites_subtitle': 'Accesos guardados en WizZ', 'color_studio.hue_purity': 'H {hue}° · Pureza {purity}% · Brillo {brightness}%', 'color_studio.hue_saturation': 'H {hue}° · S {saturation}% · RGB exacto', 'color_studio.live': 'En vivo', 'color_studio.live_hint': 'Los cambios visuales se envían con throttle; el drag no satura la LAN.', 'color_studio.mode_white': 'BLANCO', 'color_studio.no_pending_changes': 'No hay cambios pendientes.', 'color_studio.palette_hint': '↑ blanco / pastel   ·   ↓ color puro', 'color_studio.palette_note': 'La paleta genera RGB directo con pureza perceptual; usa Brillo para la intensidad.', 'color_studio.palette_section': 'PALETA HUE / PUREZA', 'color_studio.palette_subtitle': 'Horizontal: matiz · vertical: pureza perceptual · sin negro', 'color_studio.pending_changes': 'Cambios pendientes', 'color_studio.precise_section': 'CONTROL PRECISO', 'color_studio.precise_subtitle': 'RGB exacto se conserva hasta volver a tocar la paleta', 'color_studio.quick_subtitle': 'Colores limpios al 100%', 'color_studio.recent_section': 'RECIENTES', 'color_studio.recent_subtitle': 'Últimos colores y blancos aplicados', 'color_studio.recents_empty': 'Aún no hay colores recientes. Aplica uno para guardarlo aquí.', 'color_studio.save_current': 'Guardar actual', 'color_studio.subtitle': 'Color puro, blancos Kelvin y brillo independiente', 'color_studio.use_values': 'Usar valores', 'color_studio.view_all': 'Ver todos', 'color_studio.white_value': 'Blanco {kelvin}K', 'home.brightness_section': 'BRILLO', 'home.favorites_empty': 'Guarda colores o blancos desde Color Studio o Favoritos.', 'home.favorites_section': 'FAVORITOS', 'home.header.subtitle': 'Control principal de iluminación', 'home.header.title': 'Inicio', 'home.manage': 'Administrar', 'home.master': 'Control maestro', 'home.master_hint': 'Toca para alternar el target activo', 'home.off': 'APAGADO', 'home.on': 'ENCENDIDO', 'home.quick.cinema': 'TV / Cine', 'home.quick.cool': 'Frío', 'home.quick.party': 'Fiesta', 'home.quick.reading': 'Lectura', 'home.quick.relax': 'Relax', 'home.quick.reset': 'Reset', 'home.quick.warm': 'Cálido', 'home.quick_section': 'ACCESOS RÁPIDOS', 'home.refresh_state': 'Releer estado real', 'home.reset_brightness': 'Restaurar brillo a 100%', 'home.searching': 'Buscando…', 'home.status.no_target': 'Sin ampolleta activa', 'home.status.offline': 'Sin conexión', 'home.status.online': 'En línea', 'white.name.candle': 'Vela', 'white.name.cool': 'Frío', 'white.name.daylight': 'Día', 'white.name.home': 'Hogar', 'white.name.neutral': 'Neutro', 'white.name.warm': 'Cálido', 'white.note.daily': 'diario', 'white.note.energy': 'energía', 'white.note.focus': 'foco', 'white.note.relax': 'relax', 'white.note.soft': 'suave', 'white.note.very_warm': 'muy cálido'})
